/* Mandarin vocabulary — categorized.
   Tones encoded directly in pinyin marks (ā á ǎ à a). */
const VOCAB = {
  "Greetings": [
    { h: "你好",     p: "nǐ hǎo",         e: "hello" },
    { h: "再见",     p: "zài jiàn",       e: "goodbye" },
    { h: "谢谢",     p: "xiè xie",        e: "thank you" },
    { h: "不客气",   p: "bú kè qi",       e: "you're welcome" },
    { h: "对不起",   p: "duì bu qǐ",      e: "I'm sorry" },
    { h: "没关系",   p: "méi guān xi",    e: "it's okay" },
    { h: "早上好",   p: "zǎo shang hǎo",  e: "good morning" },
    { h: "晚安",     p: "wǎn ān",         e: "good night" },
    { h: "请",       p: "qǐng",           e: "please" },
    { h: "你好吗",   p: "nǐ hǎo ma",      e: "how are you?" },
    { h: "我很好",   p: "wǒ hěn hǎo",     e: "I'm fine" },
    { h: "欢迎",     p: "huān yíng",      e: "welcome" }
  ],
  "Numbers": [
    { h: "一",   p: "yī",    e: "one" },
    { h: "二",   p: "èr",    e: "two" },
    { h: "三",   p: "sān",   e: "three" },
    { h: "四",   p: "sì",    e: "four" },
    { h: "五",   p: "wǔ",    e: "five" },
    { h: "六",   p: "liù",   e: "six" },
    { h: "七",   p: "qī",    e: "seven" },
    { h: "八",   p: "bā",    e: "eight" },
    { h: "九",   p: "jiǔ",   e: "nine" },
    { h: "十",   p: "shí",   e: "ten" },
    { h: "百",   p: "bǎi",   e: "hundred" },
    { h: "千",   p: "qiān",  e: "thousand" }
  ],
  "Pronouns": [
    { h: "我",     p: "wǒ",       e: "I / me" },
    { h: "你",     p: "nǐ",       e: "you" },
    { h: "他",     p: "tā",       e: "he / him" },
    { h: "她",     p: "tā",       e: "she / her" },
    { h: "我们",   p: "wǒ men",   e: "we / us" },
    { h: "你们",   p: "nǐ men",   e: "you (plural)" },
    { h: "他们",   p: "tā men",   e: "they / them" },
    { h: "这",     p: "zhè",      e: "this" },
    { h: "那",     p: "nà",       e: "that" },
    { h: "什么",   p: "shén me",  e: "what" },
    { h: "谁",     p: "shéi",     e: "who" },
    { h: "哪里",   p: "nǎ lǐ",    e: "where" }
  ],
  "Family": [
    { h: "妈妈",   p: "mā ma",        e: "mom" },
    { h: "爸爸",   p: "bà ba",        e: "dad" },
    { h: "哥哥",   p: "gē ge",        e: "older brother" },
    { h: "弟弟",   p: "dì di",        e: "younger brother" },
    { h: "姐姐",   p: "jiě jie",      e: "older sister" },
    { h: "妹妹",   p: "mèi mei",      e: "younger sister" },
    { h: "爷爷",   p: "yé ye",        e: "grandpa (paternal)" },
    { h: "奶奶",   p: "nǎi nai",      e: "grandma (paternal)" },
    { h: "儿子",   p: "ér zi",        e: "son" },
    { h: "女儿",   p: "nǚ ér",        e: "daughter" },
    { h: "朋友",   p: "péng you",     e: "friend" },
    { h: "家",     p: "jiā",          e: "family / home" }
  ],
  "Food": [
    { h: "水",     p: "shuǐ",         e: "water" },
    { h: "茶",     p: "chá",          e: "tea" },
    { h: "咖啡",   p: "kā fēi",       e: "coffee" },
    { h: "米饭",   p: "mǐ fàn",       e: "rice" },
    { h: "面条",   p: "miàn tiáo",    e: "noodles" },
    { h: "面包",   p: "miàn bāo",     e: "bread" },
    { h: "鸡蛋",   p: "jī dàn",       e: "egg" },
    { h: "肉",     p: "ròu",          e: "meat" },
    { h: "鱼",     p: "yú",           e: "fish" },
    { h: "苹果",   p: "píng guǒ",     e: "apple" },
    { h: "牛奶",   p: "niú nǎi",      e: "milk" },
    { h: "好吃",   p: "hǎo chī",      e: "delicious" }
  ],
  "Colors": [
    { h: "红色",   p: "hóng sè",      e: "red" },
    { h: "蓝色",   p: "lán sè",       e: "blue" },
    { h: "黄色",   p: "huáng sè",     e: "yellow" },
    { h: "绿色",   p: "lǜ sè",        e: "green" },
    { h: "黑色",   p: "hēi sè",       e: "black" },
    { h: "白色",   p: "bái sè",       e: "white" },
    { h: "紫色",   p: "zǐ sè",        e: "purple" },
    { h: "粉色",   p: "fěn sè",       e: "pink" },
    { h: "橙色",   p: "chéng sè",     e: "orange" },
    { h: "灰色",   p: "huī sè",       e: "gray" }
  ],
  "Time": [
    { h: "今天",   p: "jīn tiān",     e: "today" },
    { h: "昨天",   p: "zuó tiān",     e: "yesterday" },
    { h: "明天",   p: "míng tiān",    e: "tomorrow" },
    { h: "现在",   p: "xiàn zài",     e: "now" },
    { h: "早上",   p: "zǎo shang",    e: "morning" },
    { h: "中午",   p: "zhōng wǔ",     e: "noon" },
    { h: "晚上",   p: "wǎn shang",    e: "evening" },
    { h: "星期一", p: "xīng qī yī",   e: "Monday" },
    { h: "星期五", p: "xīng qī wǔ",   e: "Friday" },
    { h: "星期天", p: "xīng qī tiān", e: "Sunday" },
    { h: "月",     p: "yuè",          e: "month / moon" },
    { h: "年",     p: "nián",         e: "year" }
  ],
  "Verbs": [
    { h: "是",     p: "shì",          e: "to be" },
    { h: "有",     p: "yǒu",          e: "to have" },
    { h: "去",     p: "qù",           e: "to go" },
    { h: "来",     p: "lái",          e: "to come" },
    { h: "吃",     p: "chī",          e: "to eat" },
    { h: "喝",     p: "hē",           e: "to drink" },
    { h: "看",     p: "kàn",          e: "to see / watch" },
    { h: "说",     p: "shuō",         e: "to speak" },
    { h: "做",     p: "zuò",          e: "to do / make" },
    { h: "买",     p: "mǎi",          e: "to buy" },
    { h: "想",     p: "xiǎng",        e: "to think / want" },
    { h: "爱",     p: "ài",           e: "to love" }
  ],
  "Phrases": [
    { h: "我爱你",       p: "wǒ ài nǐ",         e: "I love you" },
    { h: "我不知道",     p: "wǒ bù zhī dào",    e: "I don't know" },
    { h: "我饿了",       p: "wǒ è le",          e: "I'm hungry" },
    { h: "多少钱",       p: "duō shao qián",    e: "how much money?" },
    { h: "我叫…",       p: "wǒ jiào …",         e: "my name is …" },
    { h: "你叫什么名字", p: "nǐ jiào shén me míng zi", e: "what's your name?" },
    { h: "我是美国人",   p: "wǒ shì měi guó rén", e: "I am American" },
    { h: "我会说中文",   p: "wǒ huì shuō zhōng wén", e: "I can speak Chinese" },
    { h: "听不懂",       p: "tīng bu dǒng",     e: "I don't understand" },
    { h: "再说一遍",     p: "zài shuō yí biàn", e: "say it again" }
  ]
};
